version: 2
jobs:
  build:
    working_directory: ~/pizzapi
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            python setup.py test
            python setup.py install
      - store_test_results:
          path: test-results
